### PR TITLE
noarch, version, pypi, pip, template

### PR DESCRIPTION
**Pull request by pmlandwehr**

### CODE REVIEW

**Comment by pmlandwehr** [comment]
@conda-forge-admin please rerender

**Comment by pmlandwehr** [comment]
@conda-forge-admin please rerender

**Comment by pmlandwehr** [comment]
@conda-forge-admin please rerender

**Comment by setu4993** [comment]
Closing this since this is now done: https://github.com/conda-forge/fabric-feedstock/pull/14.

**Pull request closed without merging**
